// src/constants.ts
export const AVATARS = {
	ME: "/avatars/IMG_7729.png",
	FOOTBALL: "/avatars/IMG_7730.png",
	PEACE: "/avatars/IMG_7733.png",
	JUMP: "/avatars/IMG_7734.png",
	CELEBRATE: "/avatars/IMG_7735.png",
	BIKE: "/avatars/IMG_7737.png",
	WAVE: "/avatars/IMG_7739.png",
} as const;

export const PANELS = [
	{
		order: 1,
		id: "peace",
		title: "Main Character Energy",
		desc: "Living in the moment, like the main character—enjoying life and progressing with every step!",
		color: "bg-pink-400",
		avatar: AVATARS.PEACE,
		grid: "md:col-span-1 md:row-span-2",
		isTall: true,
		colorCode: "#fb64b6",
	},
	{
		order: 3,
		id: "move",
		title: "On the Move",
		desc: "Speeding through projects, boosting my XP and zooming toward the next big milestone!",
		color: "bg-orange-400",
		avatar: AVATARS.BIKE,
		grid: "md:col-span-2",
		colorCode: "#ff8904",
	},
	{
		order: 4,
		id: "aresenal",
		title: "The Arsenal",
		desc: "Always prepared to take on the dev-verse, whether coding a perfect move or discovering new challenges!",
		color: "bg-blue-400",
		avatar: AVATARS.CELEBRATE,
		grid: "md:col-span-1 md:row-span-2",
		isTall: true,
		colorCode: "#50a2ff",
	},
	{
		order: 5,
		id: "hands",
		title: "The Safe Hands",
		desc: "With quick reflexes and a sharp focus, grabbing every chance and ensuring nothing slips through!",
		color: "bg-green-400",
		avatar: AVATARS.FOOTBALL,
		grid: "md:col-span-1 md:row-span-1",
		colorCode: "#05df72",
	},
	{
		order: 2,
		id: "jump",
		title: "Grind for XP",
		desc: "Climbing the ranks, taking on fresh challenges, and leveling up with every move I make!",
		color: "bg-yellow-400",
		avatar: AVATARS.JUMP,
		grid: "md:col-span-1 md:row-span-1",
		colorCode: "#fdc700",
	},
	{
		order: 6,
		id: "signal",
		title: "Signal Me",
		desc: "Always alert, ready to connect and seize every opportunity that comes my way!",
		color: "bg-purple-500",
		avatar: AVATARS.ME,
		grid: "md:col-span-1 md:row-span-1",
		colorCode: "#ad46ff",
	},
] as const;
