
export const AVATARS = {
	ME: "/avatars/IMG_7729.png",
	FOOTBALL: "/avatars/IMG_7730.png",
	PEACE: "/avatars/IMG_7733.png",
	JUMP: "/avatars/IMG_7734.png",
	CELEBRATE: "/avatars/IMG_7735.png",
	BIKE: "/avatars/IMG_7737.png",
	WAVE: "/avatars/IMG_7732.PNG",
} as const;

export const PANELS = [
	{
		order: 1,
		id: "peace",
		title: "Main Character Energy",
		desc: "Living in the moment, like the main character—enjoying life and progressing with every step!",
		color: "bg-pink-400",
		avatar: AVATARS.PEACE,
		grid: "md:col-span-1 md:row-span-2",
		isTall: true,
		colorCode: "#fb64b6",
	},
	{
		order: 3,
		id: "move",
		title: "On the Move",
		desc: "Speeding through projects, boosting my XP and zooming toward the next big milestone!",
		color: "bg-orange-400",
		avatar: AVATARS.BIKE,
		grid: "md:col-span-2",
		colorCode: "#ff8904",
	},
	{
		order: 4,
		id: "aresenal",
		title: "The Arsenal",
		desc: "Always prepared to take on the dev-verse, whether coding a perfect move or discovering new challenges!",
		color: "bg-blue-400",
		avatar: AVATARS.CELEBRATE,
		grid: "md:col-span-1 md:row-span-2",
		isTall: true,
		colorCode: "#50a2ff",
	},
	{
		order: 5,
		id: "hands",
		title: "The Safe Hands",
		desc: "With quick reflexes and a sharp focus, grabbing every chance and ensuring nothing slips through!",
		color: "bg-green-400",
		avatar: AVATARS.FOOTBALL,
		grid: "md:col-span-1 md:row-span-1",
		colorCode: "#05df72",
	},
	{
		order: 2,
		id: "jump",
		title: "Grind for XP",
		desc: "Climbing the ranks, taking on fresh challenges, and leveling up with every move I make!",
		color: "bg-yellow-400",
		avatar: AVATARS.JUMP,
		grid: "md:col-span-1 md:row-span-1",
		colorCode: "#fdc700",
	},
	{
		order: 6,
		id: "signal",
		title: "Signal Me",
		desc: "Always alert, ready to connect and seize every opportunity that comes my way!",
		color: "bg-purple-500",
		avatar: AVATARS.ME,
		grid: "md:col-span-1 md:row-span-1",
		colorCode: "#ad46ff",
	},
] as const;

export const ASPIRATION_QUESTS = [
	{
		id: "Q-01",
		title: "ENTER THE 3D REALM",
		desc: "Unlocking WebGL secrets.",
		status: "IN_PROGRESS",
		borderColor: "border-sky-500",
		bg: "bg-sky-500/10",
		rotate: -1
	},
	{
		id: "Q-02",
		title: "FORGE THE GUILD",
		desc: "Assembling elite creatives.",
		status: "LOCKED",
		borderColor: "border-purple-500",
		bg: "bg-purple-500/10",
		rotate: 2
	},
	{
		id: "Q-03",
		title: "NEURAL LINKAGE",
		desc: "Integrating AI agents.",
		status: "OPEN",
		borderColor: "border-emerald-500",
		bg: "bg-emerald-500/10",
		rotate: -2
	},
	{
		id: "Q-04",
		title: "ARCHITECT'S BLUEPRINT",
		desc: "Drafting scalable SaaS.",
		status: "LOCKED",
		borderColor: "border-orange-500",
		bg: "bg-orange-500/10",
		rotate: 1
	},
	{
		id: "Q-05",
		title: "MASTER OF VOID",
		desc: "Studying low-level systems.",
		status: "LOCKED",
		borderColor: "border-rose-500",
		bg: "bg-rose-500/10",
		rotate: -1
	},
	// Duplicates for length
	{
		id: "Q-06",
		title: "QUANTUM LEAP",
		desc: "Exploring quantum computing.",
		status: "LOCKED",
		borderColor: "border-yellow-500",
		bg: "bg-yellow-500/10",
		rotate: 2
	},
	{
		id: "Q-07",
		title: "SYNTHETIC MINDS",
		desc: "Building AGI prototypes.",
		status: "LOCKED",
		borderColor: "border-pink-500",
		bg: "bg-pink-500/10",
		rotate: -2
	}
] as const;

export const HERO_COMIC_PANELS = [
	{
		src: "/avatars/IMG_7735.PNG",
		alt: "Travel",
		color: "#FFD700", // Gold
		story: "Living life one SRK pose at a time.",
		rotate: -3,
	},
	{
		src: "/avatars/IMG_7733.PNG",
		alt: "Fun",
		color: "#FF69B4", // Hot Pink
		story: "Attempting adulthood. Accidentally chose chaos.",
		rotate: 2,
	},
	{
		src: "/avatars/IMG_7734.PNG",
		alt: "Growth",
		color: "#8842ebff", // Violet
		story: "Excited for what’s next, learning as I go.",
		rotate: -2,
	},
	{
		src: "/avatars/IMG_7737.PNG",
		alt: "Biking",
		color: "#4ade80", // Light Green
		story: "Two wheels, my kind of therapy.",
		rotate: 3,
	},
] as const;

// Ordered by engineering depth, most impressive first.
export const SHELF_PROJECTS = [
	{
		id: 2,
		title: "Graphly",
		year: "2026",
		category: "Productivity",
		tech: ["React", "TypeScript", "Golang", "PostgreSQL", "WebSockets"],
		color: "#10b981",
		image: "/graphly-board.jpg",
		gif: "/graphly-demo.webp",
		time: "2026",
		shortDesc: "A real-time, multi-user issue tracker that schedules your plan as a dependency graph. It runs the critical path and a Monte Carlo forecast in the browser, so it knows what's blocked, who's holding everyone up and when work will really ship.",
		liveUrl: "https://graphly.fly.dev",
		githubUrl: "https://github.com/Lal-Jr/Graphly",
		problem: "Issue trackers store \"blocks\" links and then ignore them. The board can't tell you which issue is quietly holding up ten others, whether the due date is already lost, or what happens to the ship date if one task slips three days. Teams find out on the day it's late.",
		thought: "Every dependency is already an edge in a graph. If the tracker schedules that graph like a project planner, the questions answer themselves: the critical path sets the ship date, slack says what can wait, and a late forecast shows up weeks before the due date does.",
		solving: "The browser runs a scheduling engine: the critical path method over working days gives every open issue a forecast start and finish, epics roll up to their last child, and a Monte Carlo simulation of estimate overruns gives a confidence date. What-if slips show every issue that shifts and every due date that newly gets missed. The Go server keeps Postgres as the source of truth. Each write records an event in a transactional outbox and wakes every server over LISTEN/NOTIFY, so the app scales horizontally and clients resume from their last event after a disconnect. Adding a dependency locks the project and checks reachability with a recursive query, so two people linking A to B and B to A at the same moment can't create a cycle. The interface borrows Jira's workflow but not its look: board cards are drawn as graph nodes with ports for what they wait on and what waits on them, the forecast is pinned to the sidebar on every page, the ship date is shown as a confidence curve, and the critical path is drawn as a transit line.",
		result: "A deployed tracker with a board, list, live dependency graph, auto-scheduled Gantt timeline, standup digest and insights that rank blockers by how much they hold up and flag work that will be late before it is. It has workspaces, invites and roles, live presence, conflict-safe edits, and a GitHub webhook that moves issues along as pull requests open and merge. Go tests cover the API, realtime delivery and concurrency, and a one-click demo needs no sign-up.",
		isComingSoon: false,
	},
	{
		id: 6,
		title: "ArchFlow",
		year: "2026",
		category: "Developer Tools",
		tech: ["Next.js", "TypeScript", "React Flow", "Tailwind CSS"],
		color: "#ef4444",
		image: "/archflow-simulator.jpg",
		gif: "/archflow-demo.webp",
		time: "2026",
		shortDesc: "A distributed-systems simulator built on a from-scratch traffic engine. Draw a backend, push load through it and watch latency, queues, retry storms and failures play out live, then practice 24 real system design interview questions with graded reference designs.",
		liveUrl: "https://archflow-sim.vercel.app",
		githubUrl: "https://github.com/Lal-Jr/ArchFlow",
		problem: "System design is taught on whiteboards, and a whiteboard never pushes back. You can draw a cache, a queue and three replicas, but you never see what happens at 3,000 requests a second, which box fails first, or why a slow database turns into a slow page.",
		thought: "Make the diagram run. If every box has a capacity and every arrow carries traffic, the design can answer its own questions: where the bottleneck is, what a traffic spike does to a queue, and what breaks when a node dies.",
		solving: "I wrote a rate-based simulation engine from scratch in TypeScript. It compiles the graph once per edit (a depth-first search drops cycles, Kahn's algorithm orders the rest), then every 100ms of simulated time routes traffic forward and folds latency and failure back to the client. Components queue as they fill up, caches absorb hits, load balancers route around dead nodes, and queues back up when workers fall behind. On top of that it models retries (and the retry storms they cause), circuit breakers, autoscaling with a provisioning delay, and p99 latency from per-component latency distributions. Live metrics go through an external store, so ten updates a second never re-render the React Flow graph, and an insights layer turns the numbers into plain advice such as how many replicas would fix a bottleneck.",
		result: "A simulator with traffic patterns, chaos controls, live charts, cost estimates and bottleneck detection, plus budgeted challenges (survive Black Friday, a database outage, a retry storm). It doubles as an interview-prep course: 24 of the most-asked system design questions, each with a full guide covering requirements, API, data model, the reasoning behind every decision, follow-ups and common mistakes, alongside graded practice and a load-testable reference design. Designs can be shared as a link, and a guided tour, undo and keyboard shortcuts make it easy to pick up. 180 tests run in CI on every push, including checks that every reference design passes its own grader. It runs entirely in the browser, with no sign-up.",
		isComingSoon: false,
	},
	{
		id: 3,
		title: "RouteWise",
		year: "2026",
		category: "Planning",
		tech: ["React", "TypeScript", "Leaflet", "OSRM", "Vitest"],
		color: "#3b82f6",
		image: "/routewise-plan.jpg",
		gif: "/routewise-demo.webp",
		time: "2026",
		shortDesc: "A day-trip planner with its own constraint solver. It orders your stops around opening hours, visit lengths and priorities using real road, bike or walking times, and repairs the schedule on the fly when you run late.",
		liveUrl: "#", // TODO: add the live URL once deployed (the "Visit Live" button stays hidden while this is "#")
		githubUrl: "https://github.com/Lal-Jr/RouteWise",
		problem: "Planning a day of sightseeing is a scheduling problem pretending to be a list. Museums close, lunch has a window, and one 40-minute delay quietly breaks the rest of the day. Map apps give you directions between two points, not a plan that still works at 3pm.",
		thought: "Treat the day as a vehicle routing problem with time windows, and treat every change as a repair rather than a restart. People care most that the plan still works, then that it changed as little as possible, then that it's efficient.",
		solving: "The planning engine is pure TypeScript with no React in it. It builds a first order by cheapest insertion, then improves it with local search (relocate, swap and 2-opt moves), scoring each candidate by simulating the whole day. Plans are compared lexicographically: closing-time violations first, then the priority weight of dropped stops, then travel and waiting time, so a feasible plan always beats a shorter one and must-visit stops are never dropped. When something changes, repair escalates only as far as it has to: retime and keep the order, then reorder until the day is feasible, then drop the lowest-priority optional stops, which come back automatically if time frees up. Travel times come from OpenStreetMap routing (OSRM) with a straight-line fallback when the service is unreachable.",
		result: "A working planner with place search, map pins, routes drawn along real roads, and a live mode that steps through the day: mark stops visited, report a delay, skip a stop, and a banner explains every change the repair made. The solver and repair engine are unit tested, it needs no API keys, and it opens on a demo Paris walking day that deliberately doesn't fit, so you can watch stops get dropped and repaired straight away.",
		isComingSoon: false,
	},
	{
		id: 1,
		title: "Circle of Life",
		year: "2026",
		category: "Social",
		tech: ["Next.js", "Golang", "PostGIS", "Redis"],
		color: "#DD5E25",
		image: "/circleoflife-map.jpg",
		gif: "/circleoflife-demo.webp",
		time: "2026",
		shortDesc: "A hyper-local community board. Ask for help or start a meetup, and the people within a few kilometres see it first, ranked by how close and how urgent it is.",
		liveUrl: "https://circleoflife-web.fly.dev",
		githubUrl: "https://github.com/Lal-Jr/CircleOfLife",
		problem: "When you need jumper cables, a hand with groceries or someone to look out for a lost dog, the people who can help are a few streets away. They're just not on the same app. Neighbourhood groups bury urgent requests under old chatter, and social feeds rank by popularity, so a request two streets away ends up below something from across the city.",
		thought: "Distance should be the main thing that ranks a post. If the feed is built around where you are right now, an urgent request 300 metres away rises to the top by itself, and the map becomes the natural way to browse.",
		solving: "The Go API stores every post as a PostGIS geography point with a GiST index, so a radius query stays fast. The feed ranks in SQL with a decay score that weighs distance, age and post type, and anything under 500 m is pinned as urgent nearby activity. New posts go out over Server-Sent Events backed by Redis pub/sub, and Redis also caches feeds and runs per-user token-bucket rate limits on posts and comments. The Next.js client uses React Query for optimistic posts, comments and Helpful votes, with a Mapbox map of everything in range. JWT auth with bcrypt and server-side sanitisation with bluemonday handle the basics.",
		result: "A working app with a nearby feed, a live map, comment threads, Helpful votes, profiles and a mobile layout with bottom navigation. It runs on Fly.io with Supabase Postgres. A seeded neighbourhood of residents, requests, meetups and conversations means it's never empty, and a one-click demo account needs no sign-up.",
		isComingSoon: false,
	},
	{
		id: 4,
		title: "SubTrack",
		year: "2026",
		category: "Finance",
		tech: ["Next.js", "TypeScript", "SQLite", "PowerSync", "Supabase"],
		color: "#a855f7",
		image: "/subtrack-runway.jpg",
		gif: "/subtrack-demo.webp",
		time: "2026",
		shortDesc: "A private, offline-first subscription tracker. It parses bank statements entirely in the browser, detects recurring charges and their billing cycles, and shows what is about to leave your account, and when.",
		liveUrl: "https://sub-track-psi.vercel.app",
		githubUrl: "https://github.com/Lal-Jr/SubTrack",
		// Copy reflects the current app; see the README for the full feature list.
		problem: "Subscription trackers either want your bank login or a statement upload to their servers, or bury you in a flat list of charges. You still can't tell what is coming next, which charge will hurt, or which subscriptions are quietly piling up.",
		thought: "Keep every byte on the device, and build the app around one question: what is about to leave my account, and when? If that answer is instant and private, the rest is detail.",
		solving: "Statements (CSV and PDF) are parsed in the browser into a local SQLite database, with automatic column mapping and duplicate-safe re-imports, so overlapping statements never double count. One detection engine groups charges by merchant, infers the billing cycle from the gaps between them, and flags price changes and lapsed subscriptions. The home screen is a runway timeline where each charge is sized by its amount, next to plain-language insights such as a large annual charge coming up. Opt-in sync through PowerSync and Supabase sits behind a provider layer, so local-only stays the default.",
		result: "An installable, offline-capable PWA with a dense dashboard, a 12-month schedule built from real charge dates, a renewal calendar, backup and restore, and a phone-first layout. Parsing and detection are covered by 69 unit tests, and it loads with sample data, so anyone can try it in seconds.",
		isComingSoon: false,
	},
	{
		id: 5,
		title: "WhyIOpened",
		year: "2026",
		category: "Productivity",
		tech: ["TypeScript", "React", "Chrome MV3", "Vite"],
		color: "#ec4899", // Pink-500
		image: "/whyiopened-prompt.jpg",
		gif: "/whyiopened-demo.webp",
		time: "2026",
		shortDesc: "A Chrome extension that asks why you opened a tab, in one keypress, so you know what every tab is for when you come back to it.",
		liveUrl: "#",
		githubUrl: "https://github.com/Lal-Jr/WhyIOpened",
		problem: "Tabs pile up faster than their purpose can be remembered. An hour later there are thirty of them open and no memory of why half exist, so they stay open out of fear or get closed and lost.",
		thought: "Capture the reason at the moment the tab is opened, when it costs nothing to remember. For that to work the question has to be almost frictionless, and the answer still has to be useful later.",
		solving: "A small card appears when you first look at a new tab. Press 1 to 6 to pick Read, Research, To-do, Reference, Buy or Watch, or add an optional note with #tags. A tab opened from a link offers its parent tab's reason, which Enter accepts, and every tab records which tab it came from, so even a skipped prompt keeps some context. A background service worker tracks the tab lifecycle and re-attaches reasons to restored tabs after a browser restart.",
		result: "In progress. The prompt, a new tab page, a popup with fuzzy search, and a dashboard filterable by reason are built. Next up: snooze, auto-archive, and Chrome Tab Groups sync.",
		isComingSoon: false,
	},
] as const;

export const EXPERIENCE_DATA = [
	{
		id: "daily-planet",
		company: "Daily Planet",
		role: "Junior Developer",
		period: "2019 - 2021",
		desc: "Modernized legacy CMS systems. Automated global news reporting pipelines.",
		color: "text-sky-400",
		nodeColor: "#38bdf8",
		x: "15%",
		y: "80.56%",
		arrowRotation: -15,
		label: "Start",
	},
	{
		id: "wayne",
		company: "Wayne Enterprises",
		role: "UI/UX Developer",
		period: "2021 - 2023",
		desc: "Developed dark-mode specialized dashboards. Implemented stealth-first accessibility features.",
		color: "text-slate-400",
		nodeColor: "#94a3b8",
		x: "40%",
		y: "49.37%",
		arrowRotation: 10,
		label: "Growth",
	},
	{
		id: "stark",
		company: "Stark Industries",
		role: "Lead Frontend Engineer",
		period: "2023 - PRESENT",
		desc: "Architected reactive HUD interfaces using Next.js. Optimized performance for low-latency combat data streams.",
		color: "text-rose-400",
		nodeColor: "#fb7185",
		x: "65%",
		y: "58.19%",
		arrowRotation: -20,
		label: "Lead",
	},
	{
		id: "ai",
		company: "Future Path",
		role: "AI Integration Specialty",
		period: "ONGOING",
		desc: "Leveraging machine learning to solve complex architectural problems and crafting intelligent interfaces.",
		color: "text-green-400",
		nodeColor: "#4ade80",
		x: "85%",
		y: "37.45%",
		arrowRotation: -10,
		label: "Focus: AI",
		isSpecial: true,
	},
] as const;

// sessionStorage flag: set once the Pac-Man intro has played in this tab.
export const INTRO_SEEN_KEY = "intro-seen";

// Contact links.
export const SOCIAL_LINKS = {
	linkedin: "https://www.linkedin.com/in/laljr-harish",
} as const;
